### ISSUE TITLE
Free for Open Source at Nodejitsu

### ISSUE THREAD

**Issue by indexzero** [tubaxenor/node-packages#1]
Saw [your Tweet.](https://twitter.com/npm_tweets/status/466412483469910017) Apply for Free for Open Source hosting at Nodejitsu :+1: 

http://opensource.jit.su

**Comment by tubaxenor** [comment]
Thanks, I will give it a look :smile:

**Comment by tubaxenor** [comment]
Using heroku instead, but still thanks for the info :)
